{% set version = "0.5.10" %}

package:
  name: python-fmask
  version: {{ version }}

source:
  url: https://github.com/ubarsc/python-fmask/releases/download/pythonfmask-{{ version }}/python-fmask-{{ version }}.tar.gz
  sha256: 5df8a25af967b849d2afe4439d339e40e007f0b5af48670de5d7d3034368425c

build:
  number: 1
  skip: true  # [win and py<=27]
  script:
    - set FMASK_NOCMDLINE=1  # [win]
    - export FMASK_NOCMDLINE=1  # [not win]
    - {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv
  entry_points:
    # do both the extension (old) and no extension entry points (new - as per the docs)
    - fmask_sentinel2makeAnglesImage = fmask.cmdline.sentinel2makeAnglesImage:mainRoutine
    - fmask_sentinel2makeAnglesImage.py = fmask.cmdline.sentinel2makeAnglesImage:mainRoutine
    - fmask_sentinel2Stacked = fmask.cmdline.sentinel2Stacked:mainRoutine
    - fmask_sentinel2Stacked.py = fmask.cmdline.sentinel2Stacked:mainRoutine
    - fmask_usgsLandsatMakeAnglesImage = fmask.cmdline.usgsLandsatMakeAnglesImage:mainRoutine
    - fmask_usgsLandsatMakeAnglesImage.py = fmask.cmdline.usgsLandsatMakeAnglesImage:mainRoutine
    - fmask_usgsLandsatSaturationMask = fmask.cmdline.usgsLandsatSaturationMask:mainRoutine
    - fmask_usgsLandsatSaturationMask.py = fmask.cmdline.usgsLandsatSaturationMask:mainRoutine
    - fmask_usgsLandsatStacked = fmask.cmdline.usgsLandsatStacked:mainRoutine
    - fmask_usgsLandsatStacked.py = fmask.cmdline.usgsLandsatStacked:mainRoutine
    - fmask_usgsLandsatTOA = fmask.cmdline.usgsLandsatTOA:mainRoutine
    - fmask_usgsLandsatTOA.py = fmask.cmdline.usgsLandsatTOA:mainRoutine

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
  host:
    - python
    - pip
    - setuptools
    - numpy
  run:
    - python
    - scipy
    - gdal
    - rios

test:
  imports:
    - fmask.fmask
  commands:
    - fmask_sentinel2makeAnglesImage -h
    - fmask_sentinel2makeAnglesImage.py -h
    - fmask_sentinel2Stacked -h
    - fmask_sentinel2Stacked.py -h
    - fmask_usgsLandsatMakeAnglesImage -h
    - fmask_usgsLandsatMakeAnglesImage.py -h
    - fmask_usgsLandsatSaturationMask -h
    - fmask_usgsLandsatSaturationMask.py -h
    - fmask_usgsLandsatStacked -h
    - fmask_usgsLandsatStacked.py -h
    - fmask_usgsLandsatTOA -h
    - fmask_usgsLandsatTOA.py -h

about:
  home: http://pythonfmask.org
  license: GPL-3.0-or-later
  license_file: LICENSE.txt
  summary: Implementation in Python of the cloud and shadow algorithms known collectively as Fmask.

extra:
  recipe-maintainers:
    - gillins
    - robintw
    - danclewley
    - neilflood
