{% set version = "0.5.2" %}

package:
  name: python-fmask
  version: {{ version }}

source:
  url: https://bitbucket.org/chchrsc/python-fmask/downloads/python-fmask-{{ version }}.tar.gz
  sha256: fc594a2d811a4d7ec4b3971466ef8170d133b5eb637e69d733d259b93a99c416

build:
  number: 1000
  skip: True  # [win and py27]
  script:
    - set FMASK_NOCMDLINE=1  # [win]
    - export FMASK_NOCMDLINE=1  # [not win]
    - "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv"
  entry_points:
    - fmask_sentinel2makeAnglesImage.py = fmask.cmdline.sentinel2makeAnglesImage:mainRoutine
    - fmask_sentinel2Stacked.py = fmask.cmdline.sentinel2Stacked:mainRoutine
    - fmask_usgsLandsatMakeAnglesImage.py = fmask.cmdline.usgsLandsatMakeAnglesImage:mainRoutine
    - fmask_usgsLandsatSaturationMask.py = fmask.cmdline.usgsLandsatSaturationMask:mainRoutine
    - fmask_usgsLandsatStacked.py = fmask.cmdline.usgsLandsatStacked:mainRoutine
    - fmask_usgsLandsatTOA.py = fmask.cmdline.usgsLandsatTOA:mainRoutine

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - numpy  # [not win]
    - numpy 1.14.*  # [win]
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy
    - gdal
    - rios

test:
  imports:
    - fmask.fmask
  commands:
    - fmask_sentinel2makeAnglesImage.py -h
    - fmask_sentinel2Stacked.py -h
    - fmask_usgsLandsatMakeAnglesImage.py -h
    - fmask_usgsLandsatSaturationMask.py -h
    - fmask_usgsLandsatStacked.py -h
    - fmask_usgsLandsatTOA.py -h

about:
  home: http://pythonfmask.org
  license: GPL-3.0
  license_file: 'LICENSE.txt'
  summary: Implementation in Python of the cloud and shadow algorithms known collectively as Fmask.

extra:
  recipe-maintainers:
    - gillins
    - robintw
    - danclewley
    - neilflood
