{% set version = "0.4.4" %}

package:
  name: python-fmask
  version: {{ version }}

source:
  fn: python-fmask-{{ version }}.tar.gz
  url: https://bitbucket.org/chchrsc/python-fmask/downloads/python-fmask-{{ version }}.tar.gz
  sha256: be57a62a2ee08d90fd3d63b7388e3563e70d2016016f3d0ed3b067411431a0e2

build:
  number: 0
  script: python setup.py install

requirements:
  build:
    - python
    - numpy x.x
    - scipy
    - gdal 2.1.*
    - rios
  run:
    - python
    - numpy x.x
    - scipy
    - gdal 2.1.*
    - rios
    
test:
  imports:
    - fmask.fmask
  commands:
    - fmask_sentinel2makeAnglesImage.py -h  # [unix]
    - fmask_sentinel2Stacked.py -h  # [unix]
    - fmask_usgsLandsatMakeAnglesImage.py -h  # [unix]
    - fmask_usgsLandsatSaturationMask.py -h  # [unix]
    - fmask_usgsLandsatStacked.py -h  # [unix]
    - fmask_usgsLandsatTOA.py -h  # [unix]
    - fmask_expandWildcards fmask_sentinel2makeAnglesImage.py -h  # [win]
    - fmask_expandWildcards fmask_sentinel2Stacked.py -h  # [win]
    - fmask_expandWildcards fmask_usgsLandsatMakeAnglesImage.py -h  # [win]
    - fmask_expandWildcards fmask_usgsLandsatSaturationMask.py -h  # [win]
    - fmask_expandWildcards fmask_usgsLandsatStacked.py -h  # [win]
    - fmask_expandWildcards fmask_usgsLandsatTOA.py -h  # [win]

about:
  home: http://pythonfmask.org
  license: GPL-3.0
  summary: Implementation in Python of the cloud and shadow algorithms known collectively as Fmask.

extra:
  recipe-maintainers:
    - gillins
    - robintw
    - danclewley
    - neilflood
