{% set version = "0.5.0" %}

package:
  name: python-fmask
  version: {{ version }}

source:
  fn: python-fmask-{{ version }}.tar.gz
  url: https://bitbucket.org/chchrsc/python-fmask/downloads/python-fmask-{{ version }}.tar.gz
  sha256: a8199aa1b9ca52e7979abcdc9245360b96d1710e48e8d97b6c71d5712eea888d

build:
  number: 0
  script: python setup.py install

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - numpy
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy
    - gdal
    - rios

test:
  imports:
    - fmask.fmask
  commands:
    - fmask_sentinel2makeAnglesImage.py -h  # [unix]
    - fmask_sentinel2Stacked.py -h  # [unix]
    - fmask_usgsLandsatMakeAnglesImage.py -h  # [unix]
    - fmask_usgsLandsatSaturationMask.py -h  # [unix]
    - fmask_usgsLandsatStacked.py -h  # [unix]
    - fmask_usgsLandsatTOA.py -h  # [unix]
    - fmask_expandWildcards fmask_sentinel2makeAnglesImage.py -h  # [win]
    - fmask_expandWildcards fmask_sentinel2Stacked.py -h  # [win]
    - fmask_expandWildcards fmask_usgsLandsatMakeAnglesImage.py -h  # [win]
    - fmask_expandWildcards fmask_usgsLandsatSaturationMask.py -h  # [win]
    - fmask_expandWildcards fmask_usgsLandsatStacked.py -h  # [win]
    - fmask_expandWildcards fmask_usgsLandsatTOA.py -h  # [win]
    - conda inspect linkages -p $PREFIX python-fmask  # [not win]
    - conda inspect objects -p $PREFIX python-fmask  # [osx]

about:
  home: http://pythonfmask.org
  license: GPL-3.0
  # Not present in the tarball.
  # license_file: LICENSE.txt
  summary: Implementation in Python of the cloud and shadow algorithms known collectively as Fmask.

extra:
  recipe-maintainers:
    - gillins
    - robintw
    - danclewley
    - neilflood
