{% set version = "0.5.1" %}

package:
  name: python-fmask
  version: {{ version }}

source:
  url: https://bitbucket.org/chchrsc/python-fmask/downloads/python-fmask-{{ version }}.tar.gz
  sha256: 6b774c3fc99f6cd9e13a027e9f18cdafee86f861302c6ebf5b20374e0be6d699

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv"
  entry_points:
    - fmask_sentinel2makeAnglesImage.py = fmask.cmdline.fmask_sentinel2makeAnglesImage:mainRoutine
    - fmask_sentinel2Stacked.py = fmask.cmdline.fmask_sentinel2Stacked:mainRoutine
    - fmask_usgsLandsatMakeAnglesImage.py = fmask.cmdline.fmask_usgsLandsatMakeAnglesImage:mainRoutine
    - fmask_usgsLandsatSaturationMask.py = fmask.cmdline.fmask_usgsLandsatSaturationMask:mainRoutine
    - fmask_usgsLandsatStacked.py = fmask.cmdline.fmask_usgsLandsatStacked:mainRoutine
    - fmask_usgsLandsatTOA.py = fmask.cmdline.fmask_usgsLandsatTOA:mainRoutine

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - numpy  # [not win]
    - numpy 1.14.*  # [win]
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy
    - gdal
    - rios

test:
  imports:
    - fmask.fmask
  commands:
    - fmask_sentinel2makeAnglesImage.py -h
    - fmask_sentinel2Stacked.py -h
    - fmask_usgsLandsatMakeAnglesImage.py -h
    - fmask_usgsLandsatSaturationMask.py -h
    - fmask_usgsLandsatStacked.py -h
    - fmask_usgsLandsatTOA.py -h

about:
  home: http://pythonfmask.org
  license: GPL-3.0
  license_file: 'LICENSE.txt'
  summary: Implementation in Python of the cloud and shadow algorithms known collectively as Fmask.

extra:
  recipe-maintainers:
    - gillins
    - robintw
    - danclewley
    - neilflood
