travis:
  secure:
    BINSTAR_TOKEN: GQLuhxfGsxsH2/DcBH4b05nbCQjwJu+aR3m/JbZ61KGINRA3vDd5AxdzDYvIb+yiXnvzYtU5C0hZUS4xIbRVeJQUVytxzumvCS1mTLeUpeiNCQ8S2RO7seXFpMjtZUnq3C2gR8axH7nyKde5iq9x7kLkSFtmU6NgNCg4bxZuCGAA78wTEICLqp+0gznoo47ieXda8DlFv4/ly39FF6WZINNjfV70Sswo1z6oE/IGjBYUOOV4keECExIMrJjTAMs8G4YnTYkb4lRofUY8X22e7qemJYRyjRCIROcxBKEN9OSEO6VCpXDYNj2nPnt3wOn3fQDlKNt6KBwsfu2rjxig0z+xS7MhafVfLiqh4Cz8/e1eRt4xlplQB08G2Uh5zwhKMAnEgmWN3D/gdyHcTZPrmJS7LoRlh1sA46v3NE77qF+xhf7Hoa45rC4p2kEtwo4HcB2dchdPBZdHihpDQGYQaxoJmbbS/cVtg58OgYoe16nOS/5IudHU/HnP+rdMoXADe91QvMmpL9YSuQEX30By0RDM8k75dLhv8wKw8BTqtkY+iRyeI5LwlbNl1tN1Al2V/0JsJx3EI7dxlqrCREp0/5AB0pxO3mcm+iPo1tB+fDZjliPsiY4DuUDvwLsrZwZAuhRfD2ToMaZG05Ev7ZONIlRIumUF0o2MxsxR5REaaxs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
