travis:
  secure:
    BINSTAR_TOKEN: TKpJTWJzsCCq3YKxF0bzXigSWnET9gVPhMDk8/+vT8wjpXHeFqQfGGPhcl+7IeVSQPn0z3qkjGnoonceRiL4to1NT88Nbc3V4uhsPBgL03ct76ZQUu5C5bWx49okcW14i+8ynME42XSzkeZBBa7OWQnDlrkV0W/v5skBGWVdpXNU4D+jQBg50CvzNpWJMR+XgyIkEruXAFLnvvkimyQuMAkOtRf+ZaG8WA1GwCPdBAfPzevAbB3pN3bicBMjRgaRY/feb4sLlBhXPQeHVZiGI16sX4EQ3JqRtUKn4vxuFqmJjfFI6Ic3c/PZN2hUjskvs+Y1UDBZAyWfsfoPuNPUWb0hh6rkIthDeimdqNzAwS7Yrv9y3FINYxH34FKj1DJeDwaIJ5Z9W5in8XNUelcavvPC9VSH6wS/84NEWh6NN8RKHwblvWtMFEm3nZDEOfJeP/nQtkkT710noyKZwURBqBV7Wliq8qbKP7t7J4uHuSHaJTZm/EA/vLv6QINI0zijYRz1yBM8kzSjTHQ16t3VYJP7SN4TPF+bicWKJsx8ygPRPnvA2amMwd7ptpKVy5ayhqja87KSYUgJVBxq+9zUIoOMewy1tANEkN7bmT32sNguJIo9yx+h4jbTk0cu0MSLdq7qKTsHYtzyuTE9xGHE9oDHglu+GTcUbEHsIRTQ6rI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
